baseURL = "https://luizm.dev"
languageCode = "pt-br-us"
theme = "hugo-coder"

[params]
avatarurl = "https://avatars1.githubusercontent.com/u/6004689"
author = "Luiz Muller"
description = "Luiz Muller Blog"
Info = "DevOps Engineer"
keywords = "blog,devops,developer"
hidecredits = true

[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "About"
    weight = 2
    url = "/about"

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/luizm"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/luiz-antonio-muller-24165a14/"
