baseURL = "https://luizm.dev"
languageCode = "pt-br-us"
languagecode = "en"
theme = "hugo-coder"

[params]
author = "Luiz Muller"
description = "Luiz Muller"
Info = "DevOps Engineer"
avatarurl = "https://avatars1.githubusercontent.com/u/6004689"
favicon_32 = "https://avatars1.githubusercontent.com/u/6004689"
keywords = "blog,sre,devops,developer"
footercontent = "contact@luizm.dev"

hidecredits = true
hideCopyright = true

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/luizm"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/luiz-antonio-muller-24165a14"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@luizm.dev"
